const options = {
  "id":{
    "type":OPTIONTYPE.NOVIEW, 
    "defaultVal":""
  },
  "x":{
    "name":"x",
    "type":OPTIONTYPE.INPUTNUMBER,
    "defaultVal":50
  },
  "y":{
    "name":"y",
    "type":OPTIONTYPE.INPUTNUMBER,
    "defaultVal":50
  },
  "w":{
    "name":"宽度",
    "type":OPTIONTYPE.INPUTNUMBER,
    "defaultVal":GRID_DEF_W,
    "min":GRID_W_MIN,
    "max":GRID_W_MAX
  },
  "h":{
    "name":"高度",
    "type":OPTIONTYPE.INPUTNUMBER,
    "defaultVal":GRID_DEF_H,
    "min":GRID_H_MIN,
  }
}
